"""add qa models

Revision ID: d9a9a5ad7ac9
Revises: e47bea513fde
Create Date: 2026-08-20 17:40:49.499946
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "d9a9a5ad7ac9"
down_revision: Union[str, Sequence[str], None] = "e47bea513fde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "questions",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "origin",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "question_text",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "document_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "document_version_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "resolution_reason",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "priority",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column(
            "resolved_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "question_attempts",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "question_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "attempt_number",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "strategy",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "pipeline_version",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "answer_text",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "confidence",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "failure_reason",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "configuration",
            postgresql.JSONB(),
            nullable=False,
        ),
        sa.Column(
            "metrics",
            postgresql.JSONB(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "question_evidence",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "question_attempt_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "document_version_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "page_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "chunk_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "content_block_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "rank",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "score",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "evidence_text",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_attempt_id"],
            ["question_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["pages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["content_block_id"],
            ["content_blocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "question_feedback",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "question_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "question_attempt_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "origin",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "rating",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "is_correct",
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            "corrected_answer",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "comment",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_attempt_id"],
            ["question_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("question_feedback")
    op.drop_table("question_evidence")
    op.drop_table("question_attempts")
    op.drop_table("questions")
